## GRIB: getting latitudes, longitudes and values

In this example we will work with pressure level GRIB data. First we ensure the example file is available.

In [1]:
import earthkit.data
earthkit.data.download_example_file("tuv_pl.grib")

In [2]:
ds = earthkit.data.from_source("file", "tuv_pl.grib").sel(param="t")
ds.ls()

centre shortName    typeOfLevel  level  dataDate  dataTime stepRange  \
0   ecmf         t  isobaricInhPa   1000  20180801      1200         0   
1   ecmf         t  isobaricInhPa    850  20180801      1200         0   
2   ecmf         t  isobaricInhPa    700  20180801      1200         0   
3   ecmf         t  isobaricInhPa    500  20180801      1200         0   
4   ecmf         t  isobaricInhPa    400  20180801      1200         0   
5   ecmf         t  isobaricInhPa    300  20180801      1200         0   

  dataType  number    gridType  
0       an       0  regular_ll  
1       an       0  regular_ll  
2       an       0  regular_ll  
3       an       0  regular_ll  
4       an       0  regular_ll  
5       an       0  regular_ll

### Using the data() method

#### Fields

In [3]:
llv = ds[0].data()
llv.shape

(3, 7, 12)

Here *llv[0]* contains the latitudes, *llv[1]* the longitudes, while *llv[2]* the values. We can get e.g. the first field value as:

In [4]:
llv[2,0,0]

272.5641784667969

When using the *flatten* keyword 1D arrays are returned:

In [5]:
llv = ds[0].data(flatten=True)
llv.shape

(3, 84)

#### FieldLists

In [6]:
llv = ds.data()
llv.shape

(8, 7, 12)

We can get the first latitude as:

In [7]:
llv[0,0,0]

90.0

We can get the first longitude as:

In [8]:
llv[1,0,0]

0.0

The first value from each field can be extracted as:

In [9]:
llv[2:,0,0]

array([272.56417847, 272.53916931, 271.26531982, 255.84306335,
       244.00323486, 226.65315247])

When using the *flatten* keyword 1D arrays are returned for latitude and longitude, and the values array will be flattened per field:

In [10]:
llv = ds.data(flatten=True)
llv.shape

(8, 84)

### Using the to_latlon() and to_numpy() methods

#### Fields

In [11]:
ll = ds[0].to_latlon()
for k, v in ll.items():
    print(f"{k} shape={v.shape}")

lat shape=(7, 12)
lon shape=(7, 12)


In [12]:
v = ds[0].to_numpy()
v.shape

(7, 12)

By default both methods keep the field's shape, but we can use the *flatten* keyword to get 1D arrays:

In [13]:
ll = ds[0].to_latlon(flatten=True)
v = ds[0].to_numpy(flatten=True)
print(ll["lat"].shape)
print(ll["lon"].shape)
print(v.shape)

(84,)
(84,)
(84,)


#### FieldLists

In [14]:
ll = ds.to_latlon()
for k, v in ll.items():
    print(f"{k} shape={v.shape}")

lat shape=(7, 12)
lon shape=(7, 12)


In [15]:
v = ds.to_numpy()
v.shape

(6, 7, 12)

E.g. the first value from each field can be extracted as:

In [16]:
v[:,0,0]

array([272.56417847, 272.53916931, 271.26531982, 255.84306335,
       244.00323486, 226.65315247])

### Specifying the array type

For all the methods above we can set the array type with the *dtype* keyword both for fields and fieldlists:

In [17]:
import numpy as np
v = ds.to_numpy(dtype=np.float32)
v[:,0,0]

array([272.56418, 272.53918, 271.26532, 255.84306, 244.00323, 226.65315],
      dtype=float32)

In [18]:
llv = ds.data(dtype=np.float32)

In [19]:
llv[:,0,0]

array([ 90.     ,   0.     , 272.56418, 272.53918, 271.26532, 255.84306,
       244.00323, 226.65315], dtype=float32)