### GRIB tensor object

In [1]:
import earthkit.data

In [2]:
ds = earthkit.data.from_source("file", "tuv_pl.grib")

In [3]:
c = ds.to_tensor("param", "level")
c.shape

(3, 6, 7, 12)

In [4]:
c.to_numpy().shape

(3, 6, 7, 12)

In [5]:
c.coords

Coordinates:
  param        [str] t, u, v
  level        [int] 300, 400, 500, 700, 850, 1000
  latitude     [float64] 90.0, 60.0, 30.0, 0.0, -30.0, -60.0, -90.0
  longitude    [float64] 0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0 ,..., 330.0

#### Slicing

In [6]:
r = c[1:3,0]
r.coords

Coordinates:
  param        [str] u, v
  level        [int] 300
  latitude     [float64] 90.0, 60.0, 30.0, 0.0, -30.0, -60.0, -90.0
  longitude    [float64] 0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0 ,..., 330.0

In [7]:
a = r.to_numpy()
a.shape

(2, 1, 7, 12)

In [8]:
a[0,:,0,0]

array([10.45549011])

#### Sel

In [9]:
r = c.sel(level=slice(500, 850))
r.coords

Coordinates:
  param        [str] t, u, v
  level        [int] 500, 700, 850
  latitude     [float64] 90.0, 60.0, 30.0, 0.0, -30.0, -60.0, -90.0
  longitude    [float64] 0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0 ,..., 330.0

In [10]:
a = r.to_numpy()
a.shape

(3, 3, 7, 12)

In [11]:
a[0,:,0,0]

array([255.84306335, 271.26531982, 272.53916931])

#### Repetaed sel

In [12]:
r1 = r.sel(level=700)
r1.coords

Coordinates:
  param        [str] t, u, v
  level        [int] 700
  latitude     [float64] 90.0, 60.0, 30.0, 0.0, -30.0, -60.0, -90.0
  longitude    [float64] 0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0 ,..., 330.0

In [13]:
a1 = r1.to_numpy()
a1.shape

(3, 1, 7, 12)

In [14]:
a1[0,:,0,0]

array([271.26531982])