## GRIB: using array backends

In this example we will use a GRIB file containing 4 messages. First we ensure the file is available.

In [1]:
import earthkit.data
earthkit.data.download_example_file("test4.grib")

In [2]:
!pip install torch --quiet
!pip install array_api_compat --quiet

In [3]:
ds = earthkit.data.from_source("file", "test4.grib", array_backend="pytorch")

In [4]:
ds.ls()

centre shortName    typeOfLevel  level  dataDate  dataTime stepRange  \
0   ecmf         t  isobaricInhPa    500  20070101      1200         0   
1   ecmf         z  isobaricInhPa    500  20070101      1200         0   
2   ecmf         t  isobaricInhPa    850  20070101      1200         0   
3   ecmf         z  isobaricInhPa    850  20070101      1200         0   

  dataType  number    gridType  
0       an       0  regular_ll  
1       an       0  regular_ll  
2       an       0  regular_ll  
3       an       0  regular_ll

#### values

In [5]:
ds[0].values[:10]

tensor([228.0460, 228.0460, 228.0460, 228.0460, 228.0460, 228.0460, 228.0460,
        228.0460, 228.0460, 228.0460], dtype=torch.float64)

In [6]:
ds[0].values.shape

torch.Size([65160])

In [7]:
ds.values.shape

torch.Size([4, 65160])

#### to_array()

In [8]:
ds[0].to_array()[:2,:2]

tensor([[228.0460, 228.0460],
        [228.6085, 228.5792]], dtype=torch.float64)

In [9]:
ds.to_array().shape

torch.Size([4, 181, 360])

In [10]:
ds.to_array(flatten=True).shape

torch.Size([4, 65160])

#### Array fieldlists

In [11]:
r = ds.to_fieldlist(array_backend="pytorch")
r

ArrayFieldList(fields=4)

In [12]:
r.ls()

centre shortName    typeOfLevel  level  dataDate  dataTime stepRange  \
0   ecmf         t  isobaricInhPa    500  20070101      1200         0   
1   ecmf         z  isobaricInhPa    500  20070101      1200         0   
2   ecmf         t  isobaricInhPa    850  20070101      1200         0   
3   ecmf         z  isobaricInhPa    850  20070101      1200         0   

  dataType  number    gridType  
0       an       0  regular_ll  
1       an       0  regular_ll  
2       an       0  regular_ll  
3       an       0  regular_ll

In [13]:
r[0].values[:10]

tensor([228.0460, 228.0460, 228.0460, 228.0460, 228.0460, 228.0460, 228.0460,
        228.0460, 228.0460, 228.0460], dtype=torch.float64)

In [14]:
md = ds.metadata()
v = ds.to_array() + 2
r1 = earthkit.data.FieldList.from_array(v, md)
r1.ls()

centre shortName    typeOfLevel  level  dataDate  dataTime stepRange  \
0   ecmf         t  isobaricInhPa    500  20070101      1200         0   
1   ecmf         z  isobaricInhPa    500  20070101      1200         0   
2   ecmf         t  isobaricInhPa    850  20070101      1200         0   
3   ecmf         z  isobaricInhPa    850  20070101      1200         0   

  dataType  number    gridType  
0       an       0  regular_ll  
1       an       0  regular_ll  
2       an       0  regular_ll  
3       an       0  regular_ll

As expected, the values in *r1* are now differing by 2 from the ones in the originial FieldList (*r*).

In [15]:
r1[0].values[:10]

tensor([230.0460, 230.0460, 230.0460, 230.0460, 230.0460, 230.0460, 230.0460,
        230.0460, 230.0460, 230.0460], dtype=torch.float64)

In [16]:
path = "_from_pytroch.grib"
r1.save(path)
ds1 = earthkit.data.from_source("file", path)
ds1.ls()

centre shortName    typeOfLevel  level  dataDate  dataTime stepRange  \
0   ecmf         t  isobaricInhPa    500  20070101      1200         0   
1   ecmf         z  isobaricInhPa    500  20070101      1200         0   
2   ecmf         t  isobaricInhPa    850  20070101      1200         0   
3   ecmf         z  isobaricInhPa    850  20070101      1200         0   

  dataType  number    gridType  
0       an       0  regular_ll  
1       an       0  regular_ll  
2       an       0  regular_ll  
3       an       0  regular_ll