## GRIB: getting latitudes, longitudes and values (regular LL grid)

In this example we will work with GRIB data on a regular latitude-longitude grid. 

In [1]:
import earthkit.data as ekd

In [2]:
ds = ekd.from_source("sample", "tuv_pl.grib").sel(param="t")
ds.ls()

tuv_pl.grib:   0%|          | 0.00/4.22k [00:00<?, ?B/s]

centre shortName    typeOfLevel  level  dataDate  dataTime stepRange  \
0   ecmf         t  isobaricInhPa   1000  20180801      1200         0   
1   ecmf         t  isobaricInhPa    850  20180801      1200         0   
2   ecmf         t  isobaricInhPa    700  20180801      1200         0   
3   ecmf         t  isobaricInhPa    500  20180801      1200         0   
4   ecmf         t  isobaricInhPa    400  20180801      1200         0   
5   ecmf         t  isobaricInhPa    300  20180801      1200         0   

  dataType  number    gridType  
0       an       0  regular_ll  
1       an       0  regular_ll  
2       an       0  regular_ll  
3       an       0  regular_ll  
4       an       0  regular_ll  
5       an       0  regular_ll

In the data each field is defined on a regular latitude-longitude grid. These grids can be represented as a 2D array so the field shape is always 2 dimensional:

In [3]:
ds[0].shape

(7, 12)

### Using the data() method

#### Fields

In [4]:
llv = ds[0].data()
type(llv), llv.shape

(numpy.ndarray, (3, 7, 12))

Here *llv[0]* contains the latitudes, *llv[1]* the longitudes, while *llv[2]* the values. Each of these arrays has the same shape that of the field *(7, 12)*). 

In [5]:
print(llv[0].shape)
# first latitude
llv[0, 0, 0]

(7, 12)


90.0

In [6]:
print(llv[1].shape)
# first longitude
llv[1, 0, 0]

(7, 12)


0.0

In [7]:
print(llv[2].shape)
# first value
llv[2, 0, 0]

(7, 12)


272.5641784667969

When using the *flatten* keyword 1D arrays are returned:

In [8]:
llv = ds[0].data(flatten=True)
llv.shape

(3, 84)

#### FieldLists

In [9]:
llv = ds.data()
type(llv), llv.shape

(numpy.ndarray, (8, 7, 12))

Latitudes can be accessed as *llv[0]*.

In [10]:
print(llv[0].shape)
# first latitude
llv[0, 0, 0]

(7, 12)


90.0

Longitudes can be accessed as *llv[1]*.

In [11]:
print(llv[1].shape)
# first longitude
llv[1, 0, 0]

(7, 12)


0.0

The field values can be accessed as *llv[2:]*.

In [12]:
print(llv[2:].shape)

# first value in first field
print(llv[2, 0, 0])

# first value from all the fields
print(llv[2:, 0, 0])

(6, 7, 12)
272.5641784667969
[272.56417847 272.53916931 271.26531982 255.84306335 244.00323486
 226.65315247]


When using the *flatten* keyword 1D arrays are returned for latitude and longitude, and the values array will be flattened per field:

In [13]:
llv = ds.data(flatten=True)
llv.shape

(8, 84)

### Using the to_latlon() and to_numpy() methods

#### Fields

In [14]:
ll = ds[0].to_latlon()
for k, v in ll.items():
    print(f"{k} shape={v.shape}")

lat shape=(7, 12)
lon shape=(7, 12)


In [15]:
v = ds[0].to_numpy()
v.shape

(7, 12)

By default both methods keep the field's shape, but we can use the *flatten* keyword to get 1D arrays:

In [16]:
ll = ds[0].to_latlon(flatten=True)
v = ds[0].to_numpy(flatten=True)
print(ll["lat"].shape)
print(ll["lon"].shape)
print(v.shape)

(84,)
(84,)
(84,)


#### FieldLists

In [17]:
ll = ds.to_latlon()
for k, v in ll.items():
    print(f"{k} shape={v.shape}")

lat shape=(7, 12)
lon shape=(7, 12)


In [18]:
v = ds.to_numpy()
v.shape

(6, 7, 12)

E.g. the first value from each field can be extracted as:

In [19]:
v[:,0,0]

array([272.56417847, 272.53916931, 271.26531982, 255.84306335,
       244.00323486, 226.65315247])

### Specifying the array type

For all the methods above we can set the array type with the *dtype* keyword both for fields and fieldlists:

In [20]:
import numpy as np
v = ds.to_numpy(dtype=np.float32)
v[:,0,0]

array([272.56418, 272.53918, 271.26532, 255.84306, 244.00323, 226.65315],
      dtype=float32)

In [21]:
llv = ds.data(dtype=np.float32)

In [22]:
llv[:,0,0]

array([ 90.     ,   0.     , 272.56418, 272.53918, 271.26532, 255.84306,
       244.00323, 226.65315], dtype=float32)