### GRIB tensor object

In [1]:
import earthkit.data

In [2]:
ds = earthkit.data.from_source("file", "tuv_pl.grib")

In [3]:
t = ds.to_tensor("param", "level")
t

In [4]:
t.shape

(3, 6, 7, 12)

In [5]:
t.to_numpy().shape

(3, 6, 7, 12)

In [6]:
t.coords

Coordinates:
  param        [str] t, u, v
  level        [int] 300, 400, 500, 700, 850, 1000
  latitude     [float64] 90.0, 60.0, 30.0, 0.0, -30.0, -60.0, -90.0
  longitude    [float64] 0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0 ,..., 330.0

In [7]:
t.latitudes()

array([[ 90.,  90.,  90.,  90.,  90.,  90.,  90.,  90.,  90.,  90.,  90.,
         90.],
       [ 60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,
         60.],
       [ 30.,  30.,  30.,  30.,  30.,  30.,  30.,  30.,  30.,  30.,  30.,
         30.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.],
       [-30., -30., -30., -30., -30., -30., -30., -30., -30., -30., -30.,
        -30.],
       [-60., -60., -60., -60., -60., -60., -60., -60., -60., -60., -60.,
        -60.],
       [-90., -90., -90., -90., -90., -90., -90., -90., -90., -90., -90.,
        -90.]])

#### Slicing

In [8]:
r = t[1:3,0]
r.coords

indexes=(slice(1, 3, None), 0, slice(None, None, None), slice(None, None, None))
coords=[[1, 2]]
coords=[[1, 2], [0]]


Coordinates:
  param        [str] u, v
  level        [int] 300
  latitude     [float64] 90.0, 60.0, 30.0, 0.0, -30.0, -60.0, -90.0
  longitude    [float64] 0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0 ,..., 330.0

In [9]:
a = r.to_numpy()
a.shape

(2, 1, 7, 12)

In [10]:
a[0,:,0,0]

array([226.65315247])

#### Sel

In [11]:
r = t.sel(level=slice(500, 850))
r.coords

indexes=(slice(None, None, None), [2, 3, 4], slice(None, None, None), slice(None, None, None))
coords=[[0, 1, 2]]
coords=[[0, 1, 2], [2, 3, 4]]


Coordinates:
  param        [str] t, u, v
  level        [int] 500, 700, 850
  latitude     [float64] 90.0, 60.0, 30.0, 0.0, -30.0, -60.0, -90.0
  longitude    [float64] 0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0 ,..., 330.0

In [12]:
a = r.to_numpy()
a.shape

(3, 3, 7, 12)

In [13]:
a[0,:,0,0]

array([255.84306335, 271.26531982, 272.53916931])

#### Repetaed sel

In [14]:
r1 = r.sel(level=700)
r1.coords

indexes=(slice(None, None, None), [1], slice(None, None, None), slice(None, None, None))
coords=[[0, 1, 2]]
coords=[[0, 1, 2], [1]]


Coordinates:
  param        [str] t, u, v
  level        [int] 700
  latitude     [float64] 90.0, 60.0, 30.0, 0.0, -30.0, -60.0, -90.0
  longitude    [float64] 0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0 ,..., 330.0

In [15]:
a1 = r1.to_numpy()
a1.shape

(3, 1, 7, 12)

In [16]:
a1[0,:,0,0]

array([271.26531982])