### GRIB tensor object

In [1]:
import earthkit.data

In [2]:
ds = earthkit.data.from_source("file", "tuv_pl.grib")

#### Fieldlist based tensor

In [3]:
t = ds.to_tensor("param", "level")
t

In [4]:
t.source.head()

centre shortName    typeOfLevel  level  dataDate  dataTime stepRange  \
0   ecmf         t  isobaricInhPa    300  20180801      1200         0   
1   ecmf         t  isobaricInhPa    400  20180801      1200         0   
2   ecmf         t  isobaricInhPa    500  20180801      1200         0   
3   ecmf         t  isobaricInhPa    700  20180801      1200         0   
4   ecmf         t  isobaricInhPa    850  20180801      1200         0   

  dataType  number    gridType  
0       an       0  regular_ll  
1       an       0  regular_ll  
2       an       0  regular_ll  
3       an       0  regular_ll  
4       an       0  regular_ll

In [5]:
t.shape

(3, 6, 7, 12)

In [6]:
t.to_numpy().shape

(3, 6, 7, 12)

In [7]:
t.coords

Coordinates:
  param        [str] t, u, v
  level        [int] 300, 400, 500, 700, 850, 1000
  latitude     [float64] 90.0, 60.0, 30.0, 0.0, -30.0, -60.0, -90.0
  longitude    [float64] 0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0 ,..., 330.0

In [8]:
t.latitudes()

array([[ 90.,  90.,  90.,  90.,  90.,  90.,  90.,  90.,  90.,  90.,  90.,
         90.],
       [ 60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,
         60.],
       [ 30.,  30.,  30.,  30.,  30.,  30.,  30.,  30.,  30.,  30.,  30.,
         30.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.],
       [-30., -30., -30., -30., -30., -30., -30., -30., -30., -30., -30.,
        -30.],
       [-60., -60., -60., -60., -60., -60., -60., -60., -60., -60., -60.,
        -60.],
       [-90., -90., -90., -90., -90., -90., -90., -90., -90., -90., -90.,
        -90.]])

#### Slicing

In [9]:
r = t[1:3,0]
r.coords

Coordinates:
  param        [str] u, v
  level        [int] 300
  latitude     [float64] 90.0, 60.0, 30.0, 0.0, -30.0, -60.0, -90.0
  longitude    [float64] 0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0 ,..., 330.0

In [10]:
r.source.head()

centre shortName    typeOfLevel  level  dataDate  dataTime stepRange  \
0   ecmf         t  isobaricInhPa    300  20180801      1200         0   
1   ecmf         t  isobaricInhPa    300  20180801      1200         0   

  dataType  number    gridType  
0       an       0  regular_ll  
1       an       0  regular_ll

In [11]:
a = r.to_numpy()
a.shape

(2, 1, 7, 12)

In [12]:
a[0,:,0,0]

array([226.65315247])

#### Using sel()

In [13]:
r = t.sel(level=slice(500, 850))
r.source.head()

centre shortName    typeOfLevel  level  dataDate  dataTime stepRange  \
0   ecmf         t  isobaricInhPa    500  20180801      1200         0   
1   ecmf         t  isobaricInhPa    700  20180801      1200         0   
2   ecmf         t  isobaricInhPa    850  20180801      1200         0   
3   ecmf         t  isobaricInhPa    500  20180801      1200         0   
4   ecmf         t  isobaricInhPa    700  20180801      1200         0   

  dataType  number    gridType  
0       an       0  regular_ll  
1       an       0  regular_ll  
2       an       0  regular_ll  
3       an       0  regular_ll  
4       an       0  regular_ll

In [14]:
r.coords

Coordinates:
  param        [str] t, u, v
  level        [int] 500, 700, 850
  latitude     [float64] 90.0, 60.0, 30.0, 0.0, -30.0, -60.0, -90.0
  longitude    [float64] 0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0 ,..., 330.0

In [15]:
a = r.to_numpy()
a.shape

(3, 3, 7, 12)

In [16]:
a[0,:,0,0]

array([255.84306335, 271.26531982, 272.53916931])

#### Repetaed sel()

In [17]:
r1 = r.sel(level=700)
r1.coords

Coordinates:
  param        [str] t, u, v
  level        [int] 700
  latitude     [float64] 90.0, 60.0, 30.0, 0.0, -30.0, -60.0, -90.0
  longitude    [float64] 0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0 ,..., 330.0

In [18]:
a1 = r1.to_numpy()
a1.shape

(3, 1, 7, 12)

In [19]:
a1[0,:,0,0]

array([271.26531982])

#### Using isel()

In [20]:
r = t.isel(level=2)
r.source.head()

centre shortName    typeOfLevel  level  dataDate  dataTime stepRange  \
0   ecmf         t  isobaricInhPa    500  20180801      1200         0   
1   ecmf         t  isobaricInhPa    500  20180801      1200         0   
2   ecmf         t  isobaricInhPa    500  20180801      1200         0   

  dataType  number    gridType  
0       an       0  regular_ll  
1       an       0  regular_ll  
2       an       0  regular_ll

In [21]:
r.coords

Coordinates:
  param        [str] t, u, v
  level        [int] 500
  latitude     [float64] 90.0, 60.0, 30.0, 0.0, -30.0, -60.0, -90.0
  longitude    [float64] 0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0 ,..., 330.0

#### Creating new object

In [22]:
a = t.to_numpy()
a = a + 1
t1 = t.copy(data=a)

t1 is now decoupled from the fieldlist and stores all the values in a single ndarray.

In [23]:
t1

In [24]:
t1.coords

Coordinates:
  param        [str] t, u, v
  level        [int] 300, 400, 500, 700, 850, 1000
  latitude     [float64] 90.0, 60.0, 30.0, 0.0, -30.0, -60.0, -90.0
  longitude    [float64] 0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0 ,..., 330.0

In [25]:
t1.to_numpy()[0,0,0,0]

227.6531524658203

In [26]:
t.to_numpy()[0,0,0,0]

226.6531524658203

#### Slicing an array based object

In [27]:
t2 = t1.sel(level=500)
r.coords

Coordinates:
  param        [str] t, u, v
  level        [int] 500
  latitude     [float64] 90.0, 60.0, 30.0, 0.0, -30.0, -60.0, -90.0
  longitude    [float64] 0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0 ,..., 330.0

In [28]:
t2.to_numpy().shape

(3, 1, 7, 12)

In [29]:
t1.to_numpy().ctypes.data

140626845414400

In [32]:
t2.to_numpy().base.ctypes.data

140626845414400

In [31]:
t2.to_numpy().shape

(3, 1, 7, 12)