## list-of-dicts: defining geography

In [1]:
import numpy as np
import earthkit.data as ekd

def build_lod(data):
    prototype = {
            **data,
            "valid_datetime": "2018-08-01T09:00:00Z",
            "param": "t", 
        }
    
    lod = [
            {"level": 500, **prototype},
            {"level": 850, **prototype},
        ]
    return lod

#### Disctinct latitudes-longitudes

For structured grids, the latitudes and longitudes can be specified as distinct values, the 2D field structure will be automatically built from them.

In [2]:
data = {"latitudes": np.array([10.0, 0.0, -10.0]),
        "longitudes": np.array([20, 40.0]),
        "values": np.array([1, 2, 3, 4, 5, 6])}

ds = ekd.from_source("list-of-dicts",  build_lod(data))
ds.ls()

param  level base_datetime             valid_datetime  step number
0     t    500          None  2018-08-01T09:00:00+00:00  None   None
1     t    850          None  2018-08-01T09:00:00+00:00  None   None

In [3]:
ds[0].shape, ds[0].to_latlon(), ds[0].to_numpy()

((3, 2),
 {'lat': array([[ 10.,  10.],
         [  0.,   0.],
         [-10., -10.]]),
  'lon': array([[20., 40.],
         [20., 40.],
         [20., 40.]])},
 array([[1, 2],
        [3, 4],
        [5, 6]]))

We can define the same data by using the actual shape for the "values".

In [4]:
data = {"latitudes": np.array([10.0, 0.0, -10.0]),
        "longitudes": np.array([20, 40.0]),
        "values": np.array([[1, 2], [3, 4], [5, 6]])}

ds = ekd.from_source("list-of-dicts",  build_lod(data))
ds[0].shape, ds[0].to_latlon(), ds[0].to_numpy()

((3, 2),
 {'lat': array([[ 10.,  10.],
         [  0.,   0.],
         [-10., -10.]]),
  'lon': array([[20., 40.],
         [20., 40.],
         [20., 40.]])},
 array([[1, 2],
        [3, 4],
        [5, 6]]))

Alternatively, the "disctinctLatitudes" and "distinctLongitudes" keys can be used. The result will be the same.

In [5]:
data = {"distinctLatitudes": np.array([10.0, 0.0, -10.0]),
        "distinctLongitudes": np.array([20, 40.0]),
        "values": np.array([1, 2, 3, 4, 5, 6])}

ds = ekd.from_source("list-of-dicts",  build_lod(data))
ds[0].shape, ds[0].to_latlon(), ds[0].to_numpy()

((3, 2),
 {'lat': array([[ 10.,  10.],
         [  0.,   0.],
         [-10., -10.]]),
  'lon': array([[20., 40.],
         [20., 40.],
         [20., 40.]])},
 array([[1, 2],
        [3, 4],
        [5, 6]]))

#### Full latitudes and longitudes

The other supported case is when the "latitudes" and "longitudes" contain all the points.

This example is the same as the distinct case above but the "latitudes" and "longitudes" now contain all the grid points.

In [6]:
data = {"latitudes": np.array([10., 10., 0., 0., -10.0, -10.0]),
        "longitudes": np.array([20, 40.0, 20., 40., 20., 40.]),
        "values": np.array([1, 2, 3, 4, 5, 6])}

ds = ekd.from_source("list-of-dicts",  build_lod(data))
ds[0].shape, ds[0].to_latlon(), ds[0].to_numpy()

((6,),
 {'lat': array([ 10.,  10.,   0.,   0., -10., -10.]),
  'lon': array([20., 40., 20., 40., 20., 40.])},
 array([1, 2, 3, 4, 5, 6]))

We can introduce the 2D structure by using a proper shape either in the "latitudes"/"longitudes" or the "values". The field's shape will be the one with the higher dimensionality.

In [7]:
data = {"latitudes": np.array([[10., 10.], [0., 0.], [-10.0, -10.0]]),
        "longitudes": np.array([[20.0, 40.], [20., 40.], [20., 40.]]),
        "values": np.array([1, 2, 3, 4, 5, 6])}

ds = ekd.from_source("list-of-dicts",  build_lod(data))
ds[0].shape, ds[0].to_latlon(), ds[0].to_numpy()

((3, 2),
 {'lat': array([[ 10.,  10.],
         [  0.,   0.],
         [-10., -10.]]),
  'lon': array([[20., 40.],
         [20., 40.],
         [20., 40.]])},
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In this mode we are free to use arbitrary "latitudes" and "longitudes" without having any structure.

In [8]:
data = {"latitudes": np.array([10., 10., 6., 6., 6.]),
        "longitudes": np.array([20, 40.0, -40., 0., 40.]),
        "values": np.array([1, 2, 3, 4, 5])}

ds = ekd.from_source("list-of-dicts",  build_lod(data))
ds[0].shape, ds[0].to_latlon(), ds[0].to_numpy()

((5,),
 {'lat': array([10., 10.,  6.,  6.,  6.]),
  'lon': array([ 20.,  40., -40.,   0.,  40.])},
 array([1, 2, 3, 4, 5]))