### GRIB tensor object

In [1]:
import earthkit.data

In [2]:
ds = earthkit.data.from_source("file", "tuv_pl.grib")

#### Fieldlist based tensor

In [3]:
t = ds.to_tensor("param", "level")
t

Finding coords in dataset for ('param', 'level'):   0%|          | 0.00/18.0 [00:00<?, ?B/s]

In [4]:
t.source.head()

centre shortName    typeOfLevel  level  dataDate  dataTime stepRange  \
0   ecmf         t  isobaricInhPa    300  20180801      1200         0   
1   ecmf         t  isobaricInhPa    400  20180801      1200         0   
2   ecmf         t  isobaricInhPa    500  20180801      1200         0   
3   ecmf         t  isobaricInhPa    700  20180801      1200         0   
4   ecmf         t  isobaricInhPa    850  20180801      1200         0   

  dataType  number    gridType  
0       an       0  regular_ll  
1       an       0  regular_ll  
2       an       0  regular_ll  
3       an       0  regular_ll  
4       an       0  regular_ll

In [5]:
t.full_shape

(3, 6, 7, 12)

In [6]:
t.to_numpy().shape

(3, 6, 7, 12)

In [7]:
t.user_coords

Coordinates:
  param    [str] t, u, v
  level    [int] 300, 400, 500, 700, 850, 1000

In [8]:
t.field_coords

{'latitude': array([ 90.,  60.,  30.,   0., -30., -60., -90.]),
 'longitude': array([  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
        330.])}

In [9]:
t.latitudes()

array([[ 90.,  90.,  90.,  90.,  90.,  90.,  90.,  90.,  90.,  90.,  90.,
         90.],
       [ 60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,
         60.],
       [ 30.,  30.,  30.,  30.,  30.,  30.,  30.,  30.,  30.,  30.,  30.,
         30.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.],
       [-30., -30., -30., -30., -30., -30., -30., -30., -30., -30., -30.,
        -30.],
       [-60., -60., -60., -60., -60., -60., -60., -60., -60., -60., -60.,
        -60.],
       [-90., -90., -90., -90., -90., -90., -90., -90., -90., -90., -90.,
        -90.]])

#### Slicing

In [10]:
r = t[1:3,0]
r.full_coords

{'param': ['u', 'v'],
 'level': [300],
 'latitude': array([ 90.,  60.,  30.,   0., -30., -60., -90.]),
 'longitude': array([  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
        330.])}

In [11]:
r.source.head()

centre shortName    typeOfLevel  level  dataDate  dataTime stepRange  \
0   ecmf         u  isobaricInhPa    300  20180801      1200         0   
1   ecmf         v  isobaricInhPa    300  20180801      1200         0   

  dataType  number    gridType  
0       an       0  regular_ll  
1       an       0  regular_ll

In [12]:
a = r.to_numpy()
a.shape

(2, 1, 7, 12)

In [13]:
a[0,:,0,0]

array([10.45549011])

#### Using sel()

In [14]:
r = t.sel(level=slice(500, 850))
r.source.head()

centre shortName    typeOfLevel  level  dataDate  dataTime stepRange  \
0   ecmf         t  isobaricInhPa    500  20180801      1200         0   
1   ecmf         t  isobaricInhPa    700  20180801      1200         0   
2   ecmf         t  isobaricInhPa    850  20180801      1200         0   
3   ecmf         u  isobaricInhPa    500  20180801      1200         0   
4   ecmf         u  isobaricInhPa    700  20180801      1200         0   

  dataType  number    gridType  
0       an       0  regular_ll  
1       an       0  regular_ll  
2       an       0  regular_ll  
3       an       0  regular_ll  
4       an       0  regular_ll

In [15]:
r.user_coords

Coordinates:
  param    [str] t, u, v
  level    [int] 500, 700, 850

In [16]:
a = r.to_numpy()
a.shape

(3, 3, 7, 12)

In [17]:
a[0,:,0,0]

array([255.84306335, 271.26531982, 272.53916931])

#### Repetaed sel()

In [18]:
r1 = r.sel(level=700)
r1.user_coords

Coordinates:
  param    [str] t, u, v
  level    [int] 700

In [19]:
a1 = r1.to_numpy()
a1.shape

(3, 1, 7, 12)

In [20]:
a1[0,:,0,0]

array([271.26531982])

#### Using isel()

In [21]:
r = t.isel(level=2)
r.source.head()

centre shortName    typeOfLevel  level  dataDate  dataTime stepRange  \
0   ecmf         t  isobaricInhPa    500  20180801      1200         0   
1   ecmf         u  isobaricInhPa    500  20180801      1200         0   
2   ecmf         v  isobaricInhPa    500  20180801      1200         0   

  dataType  number    gridType  
0       an       0  regular_ll  
1       an       0  regular_ll  
2       an       0  regular_ll

In [22]:
r.user_coords

Coordinates:
  param    [str] t, u, v
  level    [int] 500