In [1]:
import earthkit.data as ekd
ds = ekd.from_source("file", "../../examples/tuv_pl.grib")

In [2]:
f = ds[0]

In [3]:
f.time

In [4]:
f.valid_datetime

datetime.datetime(2018, 8, 1, 12, 0)

In [5]:
f.base_datetime

datetime.datetime(2018, 8, 1, 12, 0)

In [6]:
f.step

datetime.timedelta(0)

In [7]:
f.forecast_period

datetime.timedelta(0)

In [8]:
f.forecast_reference_time

datetime.datetime(2018, 8, 1, 12, 0)

In [9]:
f.latitudes.shape

(7, 12)

In [10]:
f.longitudes.shape

(7, 12)

In [11]:
f.latitudes[0:3], f.longitudes[0:3]

(array([[90., 90., 90., 90., 90., 90., 90., 90., 90., 90., 90., 90.],
        [60., 60., 60., 60., 60., 60., 60., 60., 60., 60., 60., 60.],
        [30., 30., 30., 30., 30., 30., 30., 30., 30., 30., 30., 30.]]),
 array([[  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
         330.],
        [  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
         330.],
        [  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
         330.]]))

In [12]:
#f.projection

In [13]:
f.level

1000

In [14]:
f.vertical_type

'pressure'

In [15]:
f.variable

't'

In [16]:
f.units

'K'

In [17]:
f.member

GribEnsembleBuilder.build: {'member': 0}


'0'

In [18]:
f.values.shape

(84,)

In [19]:
f.to_numpy(flatten=False).shape

(7, 12)

In [20]:
f.to_array(flatten=True, array_backend="torch")

tensor([272.5642, 272.5642, 272.5642, 272.5642, 272.5642, 272.5642, 272.5642,
        272.5642, 272.5642, 272.5642, 272.5642, 272.5642, 288.5642, 296.5642,
        288.5642, 288.5642, 288.5642, 288.5642, 280.5642, 288.5642, 296.5642,
        288.5642, 280.5642, 280.5642, 312.5642, 304.5642, 320.5642, 296.5642,
        304.5642, 296.5642, 296.5642, 296.5642, 288.5642, 296.5642, 296.5642,
        296.5642, 296.5642, 304.5642, 296.5642, 304.5642, 296.5642, 296.5642,
        296.5642, 296.5642, 296.5642, 296.5642, 296.5642, 296.5642, 288.5642,
        296.5642, 288.5642, 288.5642, 280.5642, 288.5642, 288.5642, 288.5642,
        288.5642, 288.5642, 280.5642, 288.5642, 272.5642, 264.5642, 264.5642,
        272.5642, 272.5642, 272.5642, 280.5642, 272.5642, 264.5642, 264.5642,
        272.5642, 272.5642, 240.5642, 240.5642, 240.5642, 240.5642, 240.5642,
        240.5642, 240.5642, 240.5642, 240.5642, 240.5642, 240.5642, 240.5642],
       dtype=torch.float64)

In [21]:
f.to_numpy(dtype="float32").dtype

dtype('float32')

In [22]:
v = f.values
f1 = f.set(values=v+1)
f.values.max(), f1.values.max()

(np.float64(320.5641784667969), np.float64(321.5641784667969))

In [23]:
f1.base_datetime

datetime.datetime(2018, 8, 1, 12, 0)

In [24]:
f.get("grib.class")

'od'

In [25]:
# ds.ls()

In [26]:
f.get("grib.bitsPerValue")

4

In [27]:
f.get("valid_datetime")

datetime.datetime(2018, 8, 1, 12, 0)

In [28]:
f.get("time.valid_datetime")

datetime.datetime(2018, 8, 1, 12, 0)

In [29]:
f1 = f.set(level=111)

In [30]:
f1.level

111

In [31]:
f1.get("grib.typeOfLevel")

'isobaricInhPa'

In [32]:
f.namespace("grib.mars")

{'grib.mars': {'domain': 'g',
  'levtype': 'pl',
  'levelist': 1000,
  'date': 20180801,
  'time': 1200,
  'step': 0,
  'param': 't',
  'class': 'od',
  'type': 'an',
  'stream': 'oper',
  'expver': '0001'}}

In [33]:
f.dump()

{'parameter': {'variable': 't', 'units': 'K'},
 'time': {'base_datetime': datetime.datetime(2018, 8, 1, 12, 0),
  'valid_datetime': datetime.datetime(2018, 8, 1, 12, 0),
  'step': datetime.timedelta(0)},
 'vertical': {'level': 1000, 'level_type': 'pressure', 'units': 'hPa'},
 'ensemble': {'member': '0'}}

In [34]:
f.dump(namespace="grib")

{'grib.ls': {'edition': 1,
  'centre': 'ecmf',
  'typeOfLevel': 'isobaricInhPa',
  'level': 1000,
  'dataDate': 20180801,
  'stepRange': '0',
  'dataType': 'an',
  'shortName': 't',
  'packingType': 'grid_simple',
  'gridType': 'regular_ll'},
 'grib.geography': {'Ni': 12,
  'Nj': 7,
  'latitudeOfFirstGridPointInDegrees': 90.0,
  'longitudeOfFirstGridPointInDegrees': 0.0,
  'latitudeOfLastGridPointInDegrees': -90.0,
  'longitudeOfLastGridPointInDegrees': 330.0,
  'iScansNegatively': 0,
  'jScansPositively': 0,
  'jPointsAreConsecutive': 0,
  'jDirectionIncrementInDegrees': 30.0,
  'iDirectionIncrementInDegrees': 30.0,
  'gridType': 'regular_ll'},
 'grib.mars': {'domain': 'g',
  'levtype': 'pl',
  'levelist': 1000,
  'date': 20180801,
  'time': 1200,
  'step': 0,
  'param': 't',
  'class': 'od',
  'type': 'an',
  'stream': 'oper',
  'expver': '0001'},
 'grib.parameter': {'centre': 'ecmf',
  'paramId': 130,
  'units': 'K',
  'name': 'Temperature',
  'shortName': 't'},
 'grib.statistics': {'max': 320.5641784667969,
  'min': 240.56417846679688,
  'avg': 279.70703560965404,
  'sd': 19.67421739058438,
  'skew': -0.7312302105044428,
  'kurt': -0.16904561574741717,
  'const': 0.0},
 'grib.time': {'dataDate': 20180801,
  'dataTime': 1200,
  'stepUnits': 1,
  'stepType': 'instant',
  'stepRange': '0',
  'startStep': 0,
  'endStep': 0,
  'validityDate': 20180801,
  'validityTime': 1200},
 'grib.vertical': {'typeOfLevel': 'isobaricInhPa', 'level': 1000}}