In [1]:
import earthkit.data as ekd
ds = ekd.from_source("file", "../../examples/tuv_pl.grib")

In [2]:
f = ds[0]

In [3]:
f.time

In [4]:
f.time.valid_datetime()

datetime.datetime(2018, 8, 1, 12, 0)

In [5]:
f.time.base_datetime()

datetime.datetime(2018, 8, 1, 12, 0)

In [6]:
f.time.step()

datetime.timedelta(0)

In [7]:
f.time.forecast_period()

datetime.timedelta(0)

In [8]:
f.time.forecast_reference_time()

datetime.datetime(2018, 8, 1, 12, 0)

In [9]:
f.geography.latitudes().shape

(7, 12)

In [10]:
f.geography.longitudes().shape

(7, 12)

In [11]:
f.geography.latitudes()[0:3], f.geography.longitudes()[0:3]

(array([[90., 90., 90., 90., 90., 90., 90., 90., 90., 90., 90., 90.],
        [60., 60., 60., 60., 60., 60., 60., 60., 60., 60., 60., 60.],
        [30., 30., 30., 30., 30., 30., 30., 30., 30., 30., 30., 30.]]),
 array([[  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
         330.],
        [  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
         330.],
        [  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
         330.]]))

In [12]:
#f.projection

In [13]:
f.vertical.level()

1000

In [14]:
f.vertical.type()

'pressure'

In [15]:
f.parameter.variable()

't'

In [16]:
f.parameter.units()

'K'

In [17]:
f.ensemble.member()

'0'

In [18]:
f.values.shape

(84,)

In [19]:
f.to_numpy(flatten=False).shape

(7, 12)

In [20]:
f.to_array(flatten=True, array_backend="torch")

tensor([272.5642, 272.5642, 272.5642, 272.5642, 272.5642, 272.5642, 272.5642,
        272.5642, 272.5642, 272.5642, 272.5642, 272.5642, 288.5642, 296.5642,
        288.5642, 288.5642, 288.5642, 288.5642, 280.5642, 288.5642, 296.5642,
        288.5642, 280.5642, 280.5642, 312.5642, 304.5642, 320.5642, 296.5642,
        304.5642, 296.5642, 296.5642, 296.5642, 288.5642, 296.5642, 296.5642,
        296.5642, 296.5642, 304.5642, 296.5642, 304.5642, 296.5642, 296.5642,
        296.5642, 296.5642, 296.5642, 296.5642, 296.5642, 296.5642, 288.5642,
        296.5642, 288.5642, 288.5642, 280.5642, 288.5642, 288.5642, 288.5642,
        288.5642, 288.5642, 280.5642, 288.5642, 272.5642, 264.5642, 264.5642,
        272.5642, 272.5642, 272.5642, 280.5642, 272.5642, 264.5642, 264.5642,
        272.5642, 272.5642, 240.5642, 240.5642, 240.5642, 240.5642, 240.5642,
        240.5642, 240.5642, 240.5642, 240.5642, 240.5642, 240.5642, 240.5642],
       dtype=torch.float64)

In [21]:
f.to_numpy(dtype="float32").dtype

dtype('float32')

In [22]:
v = f.values
f1 = f.set(values=v+1)
f.values.max(), f1.values.max()

(np.float64(320.5641784667969), np.float64(321.5641784667969))

In [23]:
f1.time.base_datetime()

datetime.datetime(2018, 8, 1, 12, 0)

In [24]:
f.get("metadata.class")

'od'

In [25]:
# ds.ls()

In [26]:
f.get("metadata.bitsPerValue")

4

In [27]:
f.get("time.valid_datetime")

datetime.datetime(2018, 8, 1, 12, 0)

In [28]:
f1 = f.set({"vertical.level": 111})

In [29]:
f1.vertical.level()

111

In [30]:
f1.get("metadata.typeOfLevel")

'isobaricInhPa'

In [31]:
#f.namespace("grib.mars")

In [32]:
#f.dump()

In [33]:
#f.dump(namespace="grib")