##  Xarray field

In [1]:
import earthkit.data as ekd

ds = ekd.from_source("sample", "pl.nc")
ds.ds

pl.nc:   0%|          | 0.00/200k [00:00<?, ?B/s]

<xarray.Dataset> Size: 176kB
Dimensions:                  (forecast_reference_time: 4, step: 2, level: 2,
                              latitude: 19, longitude: 36)
Coordinates:
  * forecast_reference_time  (forecast_reference_time) datetime64[ns] 32B 202...
  * step                     (step) timedelta64[ns] 16B 00:00:00 06:00:00
  * level                    (level) int64 16B 500 700
  * latitude                 (latitude) float64 152B 90.0 80.0 ... -80.0 -90.0
  * longitude                (longitude) float64 288B 0.0 10.0 ... 340.0 350.0
Data variables:
    r                        (forecast_reference_time, step, level, latitude, longitude) float64 88kB ...
    t                        (forecast_reference_time, step, level, latitude, longitude) float64 88kB ...
Attributes:
    class:        od
    stream:       oper
    levtype:      pl
    type:         fc
    expver:       0001
    date:         20240603
    time:         0
    domain:       g
    number:       0
    Conventions:  CF-1.8
    institution:  ECMWF

In [2]:
ds.head()

variable      valid_datetime       base_datetime            step  level  \
0        r 2024-06-03 00:00:00 2024-06-03 00:00:00 0 days 00:00:00    500   
1        r 2024-06-03 00:00:00 2024-06-03 00:00:00 0 days 00:00:00    700   
2        r 2024-06-03 06:00:00 2024-06-03 00:00:00 0 days 06:00:00    500   
3        r 2024-06-03 06:00:00 2024-06-03 00:00:00 0 days 06:00:00    700   
4        r 2024-06-03 12:00:00 2024-06-03 12:00:00 0 days 00:00:00    500   

  level_type number grid_type  
0       None   None      None  
1       None   None      None  
2       None   None      None  
3       None   None      None  
4       None   None      None

In [3]:
f = ds[3]

#### Time

In [4]:
f.base_datetime, f.valid_datetime, f.step

(datetime.datetime(2024, 6, 3, 0, 0),
 datetime.datetime(2024, 6, 3, 6, 0),
 datetime.timedelta(seconds=21600))

In [5]:
f.time.base_datetime, f.time.valid_datetime, f.time.step

(datetime.datetime(2024, 6, 3, 0, 0),
 datetime.datetime(2024, 6, 3, 6, 0),
 datetime.timedelta(seconds=21600))

In [6]:
for k in ["valid_datetime", "time.valid_datetime", "time_valid_datetime"]:
    print(f.get(k))

2024-06-03 06:00:00
2024-06-03 06:00:00
2024-06-03 06:00:00


#### Vertical

In [7]:
f.level, f.vertical_type

(700, 'pressure')

In [8]:
f.vertical.level, f.vertical.type

(700, 'pressure')

In [9]:
f.get("level")

700

In [10]:
f.vertical

Vertical(level=700, units=hPa, type=pressure)

In [11]:
f.vertical.units, f.vertical.positive

('hPa', 'down')

In [12]:
f.vertical.cf

{'standard_name': 'air_pressure', 'long_name': 'pressure'}

#### Geo

In [13]:
f.shape

(19, 36)

In [14]:
f.latitudes.shape, f.latitudes[0:2]

((19, 36),
 array([[90., 90., 90., 90., 90., 90., 90., 90., 90., 90., 90., 90., 90.,
         90., 90., 90., 90., 90., 90., 90., 90., 90., 90., 90., 90., 90.,
         90., 90., 90., 90., 90., 90., 90., 90., 90., 90.],
        [80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80.,
         80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80.,
         80., 80., 80., 80., 80., 80., 80., 80., 80., 80.]]))

In [15]:
f.longitudes.shape, f.longitudes[0:2]

((19, 36),
 array([[  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.,
         110., 120., 130., 140., 150., 160., 170., 180., 190., 200., 210.,
         220., 230., 240., 250., 260., 270., 280., 290., 300., 310., 320.,
         330., 340., 350.],
        [  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.,
         110., 120., 130., 140., 150., 160., 170., 180., 190., 200., 210.,
         220., 230., 240., 250., 260., 270., 280., 290., 300., 310., 320.,
         330., 340., 350.]]))

#### Values

In [16]:
f.values.shape, f.values[0:2]

((684,), array([57.20194507, 57.20194507]))

In [17]:
f.to_numpy().shape, f.to_numpy()[0:2,0:2]

((19, 36),
 array([[57.20194507, 57.20194507],
        [77.00663257, 73.62772632]]))

#### Labels

In [18]:
f1 = f.set(my_label_1=12, my_label_2="www")
f1.get("my_label_1", "my_label_2")

(12, 'www')

#### Sel

In [19]:
# step = np.timedelta64(datetime.timedelta(hours=6))
ds1 = ds.sel(variable="r", level=500)
ds1.ls()


variable      valid_datetime       base_datetime            step  level  \
0        r 2024-06-03 00:00:00 2024-06-03 00:00:00 0 days 00:00:00    500   
1        r 2024-06-03 06:00:00 2024-06-03 00:00:00 0 days 06:00:00    500   
2        r 2024-06-03 12:00:00 2024-06-03 12:00:00 0 days 00:00:00    500   
3        r 2024-06-03 18:00:00 2024-06-03 12:00:00 0 days 06:00:00    500   
4        r 2024-06-04 00:00:00 2024-06-04 00:00:00 0 days 00:00:00    500   
5        r 2024-06-04 06:00:00 2024-06-04 00:00:00 0 days 06:00:00    500   
6        r 2024-06-04 12:00:00 2024-06-04 12:00:00 0 days 00:00:00    500   
7        r 2024-06-04 18:00:00 2024-06-04 12:00:00 0 days 06:00:00    500   

  level_type number grid_type  
0       None   None      None  
1       None   None      None  
2       None   None      None  
3       None   None      None  
4       None   None      None  
5       None   None      None  
6       None   None      None  
7       None   None      None

#### Modification

In [20]:
f1 = f.set(step=12) # default is hours
f1.base_datetime, f1.valid_datetime, f1.step

(datetime.datetime(2024, 6, 3, 0, 0),
 datetime.datetime(2024, 6, 3, 12, 0),
 datetime.timedelta(seconds=43200))

In [21]:
f1 = f.set(level=500)
f1.level, f1.vertical.level, f1.get("level")

(500, 500, 500)

In [22]:
# get new data
ff  = ekd.from_source("sample", "O32_t2.grib2")[0]
lat = ff.latitudes
lon = ff.longitudes
vals = ff.values
print("new geo+vals shape:", vals.shape)

# set new data
f1 = f.set(values=vals, latitudes=lat, longitudes=lon)
f1.shape, f1.latitudes.shape, f1.longitudes.shape

O32_t2.grib2:   0%|          | 0.00/31.4k [00:00<?, ?B/s]

new geo+vals shape: (5248,)


((5248,), (5248,), (5248,))

In [23]:
# sanity check
import numpy as np
assert np.allclose(f1.values, vals)
assert np.allclose(f1.latitudes, lat)
assert np.allclose(f1.longitudes, lon)

# original metadata is kept
f1.base_datetime, f1.valid_datetime, f1.step, f1.level, f1.vertical_type

(datetime.datetime(2024, 6, 3, 0, 0),
 datetime.datetime(2024, 6, 3, 6, 0),
 datetime.timedelta(seconds=21600),
 700,
 'pressure')